line-length = 100

[lint]
select = [
    "I", # fix / sort imports
    "E", # pycodestyle errors
    "F", # pyflakes
    "A", # flake8-builtins
    "B", # flake8-bugbear
]

ignore = [
    "E111", # https://docs.astral.sh/ruff/rules/indentation-with-invalid-multiple
    "E114", # https://docs.astral.sh/ruff/rules/indentation-with-invalid-multiple-comment
    "E117", # https://docs.astral.sh/ruff/rules/over-indented
    "E501", # https://docs.astral.sh/ruff/rules/line-too-long
]
